CREATE TABLE category (id BIGINT PRIMARY KEY, name VARCHAR(100) NOT NULL);
CREATE TABLE product (id BIGINT PRIMARY KEY, name VARCHAR(100) NOT NULL,
    category_id BIGINT NOT NULL REFERENCES category(id) ON DELETE CASCADE);
