CREATE TABLE countries (id BIGINT PRIMARY KEY, name VARCHAR(100) NOT NULL);
CREATE TABLE customers (id BIGINT PRIMARY KEY, full_name VARCHAR(100) NOT NULL, country_id BIGINT NOT NULL REFERENCES countries(id));
